INFO:root:Loading data...
Traceback (most recent call last):
  File "00_scripts/05_orf_calling.py", line 307, in <module>
    main()
  File "00_scripts/05_orf_calling.py", line 267, in main
    orf_coord = read_orf(results.orf_coord)
  File "00_scripts/05_orf_calling.py", line 188, in read_orf
    orf[['pb_acc', 'misc', 'orf']] = orf['ID'].str.split('_', expand=True)
  File "/opt/conda/envs/lrpg/lib/python3.7/site-packages/pandas/core/frame.py", line 3160, in __setitem__
    self._setitem_array(key, value)
  File "/opt/conda/envs/lrpg/lib/python3.7/site-packages/pandas/core/frame.py", line 3186, in _setitem_array
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
INFO:root:Loading data...
Traceback (most recent call last):
  File "00_scripts/05_orf_calling.py", line 307, in <module>
    main()
  File "00_scripts/05_orf_calling.py", line 267, in main
    orf_coord = read_orf(results.orf_coord)
  File "00_scripts/05_orf_calling.py", line 188, in read_orf
    orf[['pb_acc', 'misc', 'orf']] = orf['ID'].str.split('_', expand=True)
  File "/opt/conda/envs/lrpg/lib/python3.7/site-packages/pandas/core/frame.py", line 3160, in __setitem__
    self._setitem_array(key, value)
  File "/opt/conda/envs/lrpg/lib/python3.7/site-packages/pandas/core/frame.py", line 3186, in _setitem_array
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
